FROM node:20-alpine

# This is a minimal base image for both ARM64 and x86_64 architectures
# No custom configuration is needed as Alpine is already small and efficient

# Set working directory
WORKDIR /app

# Define an entrypoint for the container
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# Default command to run when the container starts
CMD ["node"] 